export const serviceType = {
    1: "Movistar",
    2: "Telcel",
    3: "ATT/Iusacell",
    4: "Unefon",
    5: "Pago de Servicios",
    6: "Nextel",
    7: "Pago de Impuestos / Gobierno",
    8: "Productos Financieros",
    9: "Productos por Catálogo",
    10: "Servicios de Prepago",
    11: "Entretenimiento",
    12: "Virgin",
    13: "Otras Recargas",
    14: "Venta de Seguros",
    15: "Pago derechos de agua",
    16: "Juegos y Sorteos",
    17: "MazTiempo",
    18: "Servicios de Autopistas y Transportes",
    19: "Internet de prepago",
};
